### ISSUE TITLE
Ambiguity about storage endpoint quota

### ISSUE THREAD

**Issue by othermaciej** [whatwg/storage#103]
The [storage endpoints](https://storage.spec.whatwg.org/#storage-endpoints) section says:

> A storage endpoint also has a quota, which is null or a number representing a recommended quota (in bytes) for all storage bottles corresponding to this storage endpoint.

Does this mean the quota should be this value for the total of all storage bottles corresponding to the storage endpoint, or that each bottle corresponding to the storage endpoint should separately have this quota?

**Comment by annevk** [comment]
Good point, it's the latter (as per the normative algorithms). #104 will fix this.
