### ISSUE TITLE
Update Persistence permission section

### ISSUE THREAD

**Issue by miketaylr** [whatwg/storage#128]
As part of https://github.com/w3c/permissions/issues/263, we're making sure all the powerful features are properly hooked up in each of their specs (https://github.com/w3c/permissions/issues/329 tracks persistent-storage in particular). 

Storage looks pretty good, there's a few busted links (I guess because Permissions was recently ported from bikeshed to respec? 🤷 ). And we can hook into https://w3c.github.io/permissions/#dfn-getting-the-current-permission-state as well.

This issue tracks that work - I'll send in a PR.

**Comment by annevk** [comment]
> persistent-storage"'s permission state

This is probably wrong as "permission state" is only defined for a descriptor? (Not entirely sure how to phrase this instead though.)

Minor thing to fix: s/`{{PermissionState/"granted"}}`/`"{{PermissionState/granted}}"`/

**Comment by miketaylr** [comment]
At the very bottom of https://w3c.github.io/permissions/#reading-current-states it says (kind of easy to miss):

> As a shorthand, a PermissionName name's permission state is the permission state of a PermissionDescriptor with its name member set to name.

So we could leave it as is, or change the text to be something like:

> "persistent-storage"'s permission state must have the same value for all environment settings objects with a given origin.

`A {{PermissionDescriptor}} with its {{PermissionDescriptor/name}} set to "{{PermissionName/persistent-storage}}" must have the same <a>permission state</a> value for all <a>environment settings objects</a> with a given <a>origin</a>.`

**Comment by annevk** [comment]
Ah okay, I guess that's okay then. Although it does seem a little weird in that permission state is also an algorithm. I'm not sure if it always was like that.

**Comment by miketaylr** [comment]
> Ah okay, I guess that's okay then.

So let's close this as "done-ish". (feel free to re-open if you disagree!)
