### ISSUE TITLE
Logo is not in a circle

### ISSUE THREAD

**Issue by tabatkins** [whatwg/storage#13]
The disk logo for the spec is not in a green circle, like all other WHATWG logos are.  This is unacceptable.

I'm willing to PR this if y'all want. ^_^

**Comment by domenic** [comment]
There's actually a lot of precedent for non-circular logos when the main feature of the logo is a pointy-edged object:

- https://resources.whatwg.org/logo-compat.svg
- https://resources.whatwg.org/logo-encoding.svg
- https://resources.whatwg.org/logo-fullscreen.svg
- https://resources.whatwg.org/logo-javascript.svg
- https://resources.whatwg.org/logo-mime.svg

Looks like about 2/3 circles, 1/3 not-circles just from eyeballing https://resources.whatwg.org/

**Comment by domenic** [comment]
That said maybe the floppy disk should be "labeled" with a question mark in its big white area :P

**Comment by inexorabletash** [comment]
Don't make me redecorate! https://twitter.com/inexorabletash/status/595340856925638657

**Comment by annevk** [comment]
Perhaps a sideways question mark would fit, but @inexorabletash's argument here is quite compelling. So closing.
