### ISSUE TITLE
"obtain a storage key" needs to operate on an environment

### ISSUE THREAD

**Issue by wanderview** [whatwg/storage#137]
Currently the "obtain a storage key" algorithm operates on an environment settings object.  For service workers, however, we need to obtain a storage key from a service worker client that may just be an environment.  For example, to obtain the service worker for a client before the navigation request completes and the environment is not loaded yet.

I'd like to change these algorithms to take environment instead of environment settings object.  The origin would be extracted from the creation URL.

@annevk WDYT?

**Comment by mkruisselbrink** [comment]
Wouldn't the origin extracted from the creation URL be wrong in for example sandboxed iframes, as well as in some other opaque origin situations (i.e. a dedicated worker created by a sandboxed iframe should have the same opaque origin as its creator, for BroadcastChannel to work between them).

**Comment by wanderview** [comment]
Obtain a storage key doesn't work on opaque origins.  I guess it would matter for non-storage APIs like broadcast channel using "obtain a storage key for non-storage purposes", though.  Maybe that algorithm can only operate on environment settings.  Seems like we need an environment version of "obtain a storage key", though.

**Comment by wanderview** [comment]
Or we can write it as "if an environment settings object, then use its origin.  Otherwise compute origin from the environment creation URL".  That is what service worker client does today.

**Comment by annevk** [comment]
It sounds somewhat reasonable. https://fetch.spec.whatwg.org/#network-partition-keys does something similar (although it incorrectly says it takes an environment settings object, it's actually called with an environment at times and accounts for that).

And yeah, there's a risk that the key changes with the eventual environment. That needs to be accounted for somehow.
