### ISSUE TITLE
Add a diagram for the storage model?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/storage#151]
>To isolate this data this standard defines a [storage shed](https://storage.spec.whatwg.org/#storage-shed) which segments [storage shelves](https://storage.spec.whatwg.org/#storage-shelf) by a [storage key](https://storage.spec.whatwg.org/#storage-key). A [storage shelf](https://storage.spec.whatwg.org/#storage-shelf) in turn consists of a [storage bucket](https://storage.spec.whatwg.org/#storage-bucket) and will likely consist of multiple [storage buckets](https://storage.spec.whatwg.org/#storage-bucket) in the future to allow for different storage policies. And lastly, a [storage bucket](https://storage.spec.whatwg.org/#storage-bucket) consists of [storage bottles](https://storage.spec.whatwg.org/#storage-bottle), one for each [storage endpoint](https://storage.spec.whatwg.org/#storage-endpoint).

This is concise, but I think an image can help further to make it easier to understand. Something like:

```mermaid
erDiagram
    User-agent ||--|| Storage-shed : "holds (local)"
    Browsing-session ||--|| Storage-shed : "holds (session)"
    Storage-shed ||--o{ Storage-shelf : "for each Storage key"
    Storage-shelf ||--|| Storage-bucket : "holds (default)"
    Storage-bucket ||--|{ Storage-bottle : "for each storage endpoint"
```

**Comment by annevk** [comment]
Is there a useful tool with which we can create a diagram, make it accessible, and maintain it?

**Comment by saschanaz** [comment]
https://github.com/mermaid-js/mermaid is known, but not sure what's the best way to make the resulting SVG accessible.

**Comment by annevk** [comment]
Perhaps that's something @whatwg/a11y has experience with?

**Comment by LJWatson** [comment]
It is possible to make SVG screen reader accessible using ARIA but only to a limited degree. Essentially if the diagram can be represented as a table or lists it's achievable. It does mean having to write the SVG from scratch though, so it has the structure to support the necessary ARIA roles.

More information:
* [Accessible SVG line graphs](https://tink.uk/accessible-svg-line-graphs/) (uses ARIA to represent the data as a table)
* [Accessible SVG flowcharts](https://tink.uk/accessible-svg-flowcharts/) uses ARIA to represent the data as nested lists
For this diagram though, my suggestion is to treat the SVG like a standard image with a text description. Either pull the .svg file into an `<img>` element, or if you embed the `<svg>` element directly, then:

```
<svg role="img aria-label="Text description here">...</svg>
```

**Comment by saschanaz** [comment]
In that case maybe it can also use `aria-describedby` since my intention here is to add an image to an existing textual description.

**Comment by annevk** [comment]
Thanks! That sounds reasonable. SVG will have to be optimized through https://jakearchibald.github.io/svgomg/ as well and I guess we want to store the text input to Mermaid in a comment somewhere.

**Comment by aardrian** [comment]
> In that case maybe it can also use `aria-describedby` since my intention here is to add an image to an existing textual description.

Whatever approach you use, remember that both `aria-label` and `aria-describedby` are announced as flat text strings. While `aria-label` values are flat text strings already, `aria-describedby` can point to lists and tables and such, but will still only be announced as flat text.

**Comment by aardrian** [comment]
The [`aria-details`](https://www.w3.org/TR/wai-aria-1.1/#aria-details) property can maybe do what you want, but understand [its support is mixed](https://a11ysupport.io/tech/aria/aria-details_attribute) (what I consider poor). In other words do not rely on it unless you are prepared to test it across all targeted browser/SR combinations.

Using just a plain text reference is fine. It will also benefit more than SR users (think coga users, zoom users, sighted SR users who get even more impatient with the extra announcements, etc).
