### ISSUE TITLE
Lack of example and Explainer document

### ISSUE THREAD

**Issue by slightlyoff** [whatwg/storage#16]
In general, Chrome engineers should only be implementing new APIs that have reasonable Explainer documents attached. Re [TAG issues #85](https://github.com/w3ctag/spec-reviews/issues/85), the examples in this spec are pretty thin and there's no adjoining Explainer doc to compensate.

/cc @davidsgrogan

**Comment by annevk** [comment]
Happy to take PRs, though I'm not sure an Explainer document makes sense as we should just make the specification clearer then.

**Comment by annevk** [comment]
I added some examples. If you have some more ideas, please consider submitting a PR.
