### ISSUE TITLE
Bucket hooks

### ISSUE THREAD

**Issue by annevk** [whatwg/storage#18]
@jakearchibald @jungkees hey! I was wondering what kind of hooks you need to make it clear e.g., service worker registrations and the Cache API are stored in a box.

In #4 we are discussing the cleanup steps for when a box gets closed, but maybe we should also have formal language for actually storing something inside?

**Comment by annevk** [comment]
On IRC Jake suggested that we could just have "bucket has an associated X" where X could be service worker registrations and such. This assumes that when clearing a bucket is replaced with a new one (allowing X effectively to be GC'd as there are no more references to it). Is that the model we want? Currently we just say a bucket is cleared.

One problem is that we'd have to copy some state over from the old bucket, such as persistence and potentially more in the future once we start expanding the concept. At least, I think if you clear, you don't necessarily expect to have to invoke `persist()` again.

Thoughts?

An alternative is that a bucket has something like a specification-level GetStorageHandler(Identifier, optional ClearCallback) operation that returns a StorageHandler in which you can store stuff.

cc @inexorabletash @mikewest

**Comment by jakearchibald** [comment]
> An alternative is that a bucket has something like a specification-level GetStorageHandler(Identifier, optional ClearCallback) operation that returns a StorageHandler in which you can store stuff.

"A *bucket* has **storages**", and it's the storages that become detached.

Adding callback steps for cleanup is fine unless the order becomes observable.

**Comment by annevk** [comment]
I think the order will be observable given the combination of `navigator.storage.clear()` IDB, and Cache API. Probably also with other APIs.

https://w3c.github.io/webappsec-clear-site-data/#abstract-opdef-clear-dom-accessible-storage-for-origin deals with this through enumeration (though doesn't list the Cache API). My idea with the identifier was that we'd first sort lexicographically and then invoke the ClearCallback, but perhaps it's better to just list everything in the Storage Standard and require it to be updated as new things are added.

**Comment by jakearchibald** [comment]
> perhaps it's better to just list everything in the Storage Standard and require it to be updated as new things are added.

That seems fine. Doesn't hurt to have all origin storage referenced from one place.

**Comment by mikewest** [comment]
>  perhaps it's better to just list everything in the Storage Standard and require it to be updated as new things are added.

I'd agree that this is the right approach. `Clear-Site-Data` would be better if it deferred to Storage, rather than requiring additional enumeration of storage mechanisms.

**Comment by annevk** [comment]
FWIW, I have the feeling I'm missing a simpler solution here and as you can tell this is very much a sketch. Would love to hear your thoughts.

The idea here is to define existing storage APIs, such as service workers and localStorage, on top of these primitives so we get a well-defined Clear-Site-Data and hopefully some other benefits too. I suspect this architecture might also work for the Storage Access API in due course, though it depends a bit on how all that will pan out.

Storage APIs (e.g., localStorage) need to define:

* A **storage identifier** (a string), e.g., "localStorage". (These should match those of UsageDetails from https://github.com/whatwg/storage/pull/69/files.)
* A **replace algorithm** to abort transactions or some such in the event of storage bucket replacement. (Could be nothing if there's no cleanup to be done.)
* They need to invoke the "obtain a storage bucket area map" algorithm (outlined below) for environments that end up using the API and use the returned map as the place to store all their data.

The Storage Standard needs to define:

A registry of all storage identifiers and an easy way to get from one to its corresponding replace algorithm.

A **storage bucket** holds a **map** of storage identifiers to storage areas.

A **storage area** is a struct consisting of **map** and a **proxy map pointer set**.

(The idea is that storage area's map holds the actual storage. It's in a map because those are easy to work with. How the map is persisted is implementation-defined. How to make it available across process boundaries is implementation-defined.)

A **proxy map** has identical operations to a map and performs those on its **underlying map**.

(We hand out a proxy map to a storage API so we can replace the actual map behind the scenes.)

New algorithms:

To **obtain a storage bucket area map**, given a storage identifier _identifier_ and an environment _environment_, run these steps:

1. Let _key_ be the result of obtaining a storage key from _environment_. (This should be less hand-wavy.)
1. Let _bucket_ be the storage bucket for _key_. (This should be less hand-wavy.)
1. Let _storageArea_ be _bucket_'s map[_identifier_].
1. Let _proxyMap_ be a new proxy map.
1. Append a pointer to _proxyMap_ to _storageArea_'s proxy map pointer set.
1. Set _proxyMap_'s underlying map to _storageArea_'s map.
1. Return _proxyMap_.

(The above algorithm is intended for storage APIs. They would invoke this upon initialization to get a map to store things in.)

To **replace** a storage bucket _old_ with a storage bucket _new_, run these steps:

1. Atomically:
   1. Replace _old_ with _new_. (This should be less hand-wavy and probably talk about the site storage unit.)
   1. For each _identifier_ → _storageArea_ of _old_'s map:
      1. For each _proxyMapPointer_ of _storageArea_'s proxy map pointer set:
         1. Let _newStorageArea_ be _new_'s map[_identifier_].
         1. Set the value of _proxyMapPointer_'s underlying map to _newStorageArea_'s map.
         1. Append _proxyMapPointer_ to _newStorageArea_'s **proxy map pointer set**.
1. For each impacted agent of ...: (This should be less hand-wavy)
   1. Queue a task to:
      1. For each _identifier_ of ...:
         1. Run _identifier_'s corresponding replace algorithm with ....

(There's a couple things that need to be filled out here including what kind of details the replace algorithm might need to clean up the relevant APIs.)

**Comment by inexorabletash** [comment]
Just to be crystal clear (still waking up ☕ vs. multiple levels of indirection), the usage of the storage area's map is up to the particular storage API, i.e. for localStorage the map's keys/values are literally the (local) storage area's keys/values; for Indexed DB the keys/values would be database names/database constructs, for Cache Storage the keys/values would be cache names/caches, etc. Or a storage API could have a single entry in its storage area, and put all of its structure inside the single value. The need for this map is just because it's a common pattern across all storage APIs. 

"Storage area" as a term seems to conflict with HTML's use for localstorage, but maybe they can coalesce? Or HTML can get a new term as part of refactoring to align with this. (I don't think it's formally defined in HTML?)

I think this proposal works for Indexed DB.

**Comment by hober** [comment]
Overall, @annek, your sketch looks really good to me. One question:

> 1. Let _key_ be the result of obtaining a storage key from _environment_. (This should be less hand-wavy.)

I imagine the **obtain a storage key from an environment** algorithm could return a (registrable domain, registrable domain) tuple for partitioned storage, and a registrable domain otherwise?

**Comment by annevk** [comment]
* Yeah, the map is there so APIs don't have to design their own infrastructure. (It also isn't quite clear to me what the alternative would be.)
* Yeah, HTML needs a rewrite at which point it no longer needs the storage area it talks about. I guess one thing that's a bit unclear is `sessionStorage`. That might warrant some indirection so different sessions get their own.
* Yeah, the storage key can/needs to account for partitioning efforts.

**Comment by domenic** [comment]
Relaying some discussion from IRC:

> Let key be the result of obtaining a storage key from environment. (This should be less hand-wavy.)

I assume most of the time the storage key will be an origin. But not always. In particular this step will allow us to define both double-keying and blocking of storage.

Note that currently storage is blocked in opaque origins on a per-API basis (e.g. [localStorage](https://html.spec.whatwg.org/multipage/webstorage.html#storage-object-initialisation-steps), [idb.open()](https://w3c.github.io/IndexedDB/#dom-idbfactory-open)). Those mechanisms should probably be subsumed here, so that if _environment_ is an opaque origin, key is failure, and the rest of the algorithm fails. This also allows other scenarios to block storage by intervening at the "obtain a key" stage.

**Comment by mkruisselbrink** [comment]
Generally I think this all looks good. `sessionStorage` is definitely the odd one out, and I'm not sure quite how that would fit in here. I suppose it would get its own very special "obtaining a storage key from environment" algorithm (also currently as spec-ed, sessionStorage is the only storage mechanism that is supposed to work in opaque origins. Not implemented in chrome though).
