### ISSUE TITLE
Permissions API integration needs to be improved

### ISSUE THREAD

**Issue by annevk** [whatwg/storage#19]
See these issues:

* https://github.com/w3c/permissions/issues/74
* https://github.com/w3c/permissions/issues/33

**Comment by annevk** [comment]
See https://github.com/w3c/permissions/pull/88 for an example to follow.

**Comment by jyasskin** [comment]
You'll need to `<dfn enum-value for="PermissionName">"storage"</dfn>` or whatever name here first; let that percolate through Shepherd (@tabatkins, please add https://storage.spec.whatwg.org/ to Shepherd), and then send a PR for the Permissions API.

**Comment by tabatkins** [comment]
Added to Shepherd.
