### ISSUE TITLE
Clarify relation to existing storage APIs

### ISSUE THREAD

**Issue by jzaefferer** [whatwg/storage#24]
The introduction starts with 

> Over the years the web has grown various APIs that can be used for storage, e.g., IndexedDB, localStorage, and showNotification(). The Storage Standard consolidates these APIs by defining:

Under 3. I found this note:

> This specification primarily concerns itself with site storage.

Which helps explain why there's nothing about actually storing and retrieving data. But as of now, I can't tell, for example, how I'd actually store something in combination with `navigator.storage`.  That `StoreManager` interface doesn't expose anything that could be used to actually store something; the Promises made only contain booleans.

**Comment by annevk** [comment]
Maybe the wording should be different. The Storage Standard defines the infrastructure and a little bit of API surface around that infrastructure. All the other APIs, such as the Cache API, localStorage, IndexedDB, etc. provide APIs to store bits into the infrastructure provided by the Storage Standard.

**Comment by jzaefferer** [comment]
That seems reasonable, but it doesn't explain how I would know that my, for example, localStorage entries are persisted, since the new API seems to be completely unaware of the other APIs. Shouldn't there be a connection somewhere?

**Comment by annevk** [comment]
Yeah, that is #18 basically. We need to recast existing APIs to make sure to put their bits in the box.

**Comment by jzaefferer** [comment]
Alright, I'll follow that.
