### ISSUE TITLE
Define the behavior when calling persist() if the resource has been already used

### ISSUE THREAD

**Issue by shuangMoz** [whatwg/storage#25]
When can UA resolve promise after calling persist() if other tabs already accessed the resource? It's possible that other tabs hold the storage resources. Can the specification suggest how to deal with this situation?

**Comment by annevk** [comment]
So the scenario is that you have `https://example.com/` open twice and while using IndexedDB in one tab the other tab invokes `persist()`?

We used to have a concept of "storage mutex" in the platform, but nobody wanted to implement that, instead favoring race conditions. https://github.com/whatwg/html/issues/335#issuecomment-156498370 has some ideas of what we could settle on instead, where you send storage updates to a storage thread responsible for all storage. None of that is formalized however.

**Comment by inexorabletash** [comment]
It seems the steps for `persist()` should include an early "if origin’s site storage unit’s box is a persistent box, resolve promise with true and terminate these steps"

**Comment by annevk** [comment]
@inexorabletash I don't think that should have any effect. Or would there be a scenario where the permission is "prompt" but somehow you still got a persistent box?

**Comment by inexorabletash** [comment]
@annevk Sorry, you're right. I shouldn't read specs that soon after waking up. :)

I do notice that __permission__ as a term, the set of values, and the initial value is not defined (or referenced).

Also, Blink is planning to implement persist()'s step 3.3 as:

If _permission_ is `"prompt"`, then based on user agent heuristics determine if turning _origin_’s site storage unit’s box into a persistent box is acceptable. If it is, then set _permission_ to "granted" (and leave _permission_ unchanged otherwise).

**Comment by annevk** [comment]
Defining permission better is #19. The Permissions API is not entirely suitable just yet, though we're getting close.

Yeah, I should probably make it clear that `persist()` can also be granted without a prompt, if the user agent has determined the user is highly likely to be game.

**Comment by michael-nordman** [comment]
Maybe I don't understand the issue being raised in the OP?

> When can UA resolve promise after calling persist() if other tabs already accessed the resource? It's possible that other tabs hold the storage resources. Can the specification suggest how to deal with this situation?

I don't see a problem with an IndexedDB being opened and in use while the persistent attribute is being modified. The attribute only affects whether the user-agent is required to get user consent prior to clearing the origin's resources. The attribute applies to all existing and future resources in the box, regardless of whether an existing resource is currently in use. Where's the problem?

I think how to handle concurrent calls to persist() from multiple pages is more interesting implementation detail.

**Comment by sicking** [comment]
Indeed. I don't see a problem with allowing IndexedDB databases to remain open. Nor to allow localStorage or Cache API to continue to be used.

At least in the Gecko implementation we don't actually need to modify the storage files themselves when an origin is being persisted. We just change metadata which is stored elsewhere.

**Comment by shuangMoz** [comment]
In the Gecko implementation, persistent data storage repository is under <profile>/storage/permanent,  and temporary data storage repository is under <profile>/storage/temporary. If we call `persist()`, current Gecko implementation (QuotaManager) should move real files from temporary to permanent folder after calling persist().  And if there are other tabs open idb files, we can't move the files immediately, so it's possible we will never resolve the promise. This is why I raised this issue. I will ask Jan Varga to comment this issue.

**Comment by janvarga** [comment]
So, it depends. I told Shawn that we need to wait for all operations to finish before moving files across folders, but we can also leave files in the default storage and just update the metata file to treat given origin as persistent. The default storage currently does this for installed apps. Such origins are never evicted. Please note, that this would only work for default storage, not for temporary storage. Actual implementation won't be so easy, since we need to update some in-memory structures, etc. but it should be doable.

**Comment by annevk** [comment]
@janvarga what is the difference between "default" and "temporary" storage? Per the current specification this is expected to be a "metadata change" (we flip a bit on a box). I think ideally we keep it that way and don't allow for a more complex model where files need to move around.

(We do need to deal with that scenario though, I suppose, when clearing storage. #4 is about figuring out how to best define that.)

**Comment by janvarga** [comment]
currently, we support three independent repositiories:
<profile>/storage/default
<profile>/storage/temporary
<profile>/storage/permanent

all three can be used with IndexedDB:
indexedDB.open(name, { version: 1, storage: "default/temporary/permanent"})

1. permanent doesn't track quota at all, there's just the initial prompt for given origin
2. temporary behaves like temporary, any origin can be evicted if not used for long time
3. default behaves like temporary but some origins are treated as persistent (they are never evicted), this is currently used for installed apps

So we can rather easily enhance "default" storage to treat "marked" origins (boxes) as persistent (not just those belonging to apps).

I think .persist() would just affect the "default" storage ?

**Comment by annevk** [comment]
Yeah, I suppose. That feature is non-standard, right? So hopefully we can remove that over time once `navigator.storage.persist()` is implemented and then we no longer have to worry about "temporary" (although we introduce something like it at some point through boxes).

**Comment by janvarga** [comment]
Yeah, it's non-standard.

**Comment by sicking** [comment]
Yeah, I think we should ignore the non-"default" areas in Gecko. Most likely we should remove those after a deprecation period.

We should definitely use the "default" area in Gecko and then just adjust the removal logic to account for persisted origins.

**Comment by inexorabletash** [comment]
As an FYI, Blink supports a "persistent" bucket used only by the file system API (temporary vs. persistent must be explicitly specified on open). We're similarly just not considering that bucket when calculating quota or reasoning about the new permission.

**Comment by annevk** [comment]
I think there's agreement that the issue mentioned in OP is not an issue anymore for Firefox. The other issues mentioned have their own issues. Closing this.
