### ISSUE TITLE
The term "site" is confusing

### ISSUE THREAD

**Issue by timdream** [whatwg/storage#32]
During discussion in Mozilla London All-hands, it seems clear the term "site" has caused confusing during verbal discussion; we had to put `site: eTLD+1, e.g. example.co.uk` on the whiteboard and say "the site per spec" to avoid confusion (to the normal concept of site as used in daily life and on UI label).

Would it be easier to use a more obscure term like "origin group" so there can be a distinctive definition? The related terms like "site storage" or "site storage unit" would need to be revised as well.

**Comment by annevk** [comment]
Yeah, the usage of "site" meaning eTLD+1 and "site storage unit" meaning a unit of storage in an origin is especially confusing. We should rename those a bit.

**Comment by annevk** [comment]
Hope this is a better. Let me know if you want your name differently in the acknowledgments.
