### ISSUE TITLE
UI and origins <> origin groups

### ISSUE THREAD

**Issue by annevk** [whatwg/storage#34]
For the sake of this discussion, an origin group are all origins that share a domain label + public suffix (and have the same scheme, but not necessarily the same port).

If a user agent wants to group cookies with other kinds of storage in the UI, which is quite reasonable as they can be used to revive each other and generally share a bunch of properties, and cookies use origin group and storage and the "persistentstorage" permission uses origins, how is this reconciled?

And if the UI aligns with origin groups, does it make sense for the API to be origin-based?

I'd be interested in hearing from other implementers. I think at Mozilla we tentatively concluded that's it's probably okay to keep as much origin-bound as possible, while not necessarily surfacing that to the UI.

**Comment by foolip** [comment]
What does the "<>" in the title mean?

**Comment by annevk** [comment]
Probably something like: "versus" / "something of conflicting nature".

**Comment by foolip** [comment]
I see, I wasn't sure whether to read it as the Visual Basic inequality operator :)

**Comment by annevk** [comment]
The current text for this seems adequate to me actually. Especially after https://github.com/whatwg/storage/commit/08dbaf913976783ae9bfb9a1054d9f1e6eeb7d06.
