### ISSUE TITLE
API exposure/behavior for unique origins?

### ISSUE THREAD

**Issue by inexorabletash** [whatwg/storage#41]
Sandboxed iframes end up with unique [opaque origins](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-opaque). We should define the behavior of the API here.

One option would be to simply reject on any API call (`persist()`, `estimate()`, etc). Chrome currently does this, and it's per spec for other storage APIs (localStorage, etc). Indexed DB does this too in Chrome (not sure that's specified anywhere) 

Another would be to introduce an analogue to `[SecureContext]` that removes the API in unique opaque origins.

Or we could let unique opaque origins have some ephemeral storage, with lifetime bound to the browsing context or some such. (But please no...)

**Comment by mkruisselbrink** [comment]
(nit: they are opaque origins, not unique origins; for example a sandboxed iframe can still possibly create workers that (should) share the same opaque origin with the window)

**Comment by annevk** [comment]
Yeah sounds good. Are you writing tests by any chance? @shuangMoz do you know if we have tests for this?

**Comment by inexorabletash** [comment]
Yeah, I'll put up a PR for tests (it'll be a few days).

**Comment by inexorabletash** [comment]
Tests over at https://github.com/w3c/web-platform-tests/pull/4919

**Comment by inexorabletash** [comment]
Conversation over on the test PR have leaned towards (1) rejecting with (2) TypeError.
