### ISSUE TITLE
Clarify what persist() and persisted() do when there's an I/O error

### ISSUE THREAD

**Issue by annevk** [whatwg/storage#44]
For estimate() we throw, I think it'd be better for these to return false, unless someone can think of a reason why we'd want to expose the difference.

**Comment by annevk** [comment]
Context: https://bugzilla.mozilla.org/show_bug.cgi?id=1286717.

**Comment by inexorabletash** [comment]
From code inspection, that matches Blink behavior (resolving to false)

**Comment by annevk** [comment]
Will be impossible to test for unfortunately, though I suppose we can log a bug in case WebDriver ever gains the capability to fake I/O errors.
