### ISSUE TITLE
Clarify the expectation if pushState() data is covered by Storage Standard

### ISSUE THREAD

**Issue by shuangMoz** [whatwg/storage#50]
It's not clear to me what's the expectation if pushState() data is covered by Storage Standard. Can we clarify that a bit more? Perhaps privacy reason?

**Comment by annevk** [comment]
Yeah, the main reason is that data gets cleared together, but it probably doesn't make sense for `pushState()` data to end up persisted. It only needs to last as long as the session.

**Comment by annevk** [comment]
This should be (re)moved. This can be stored directly on the document (perhaps browsing session) and doesn't have to live longer.
