### ISSUE TITLE
Consider renaming boxes to bins or something

### ISSUE THREAD

**Issue by fantasai** [whatwg/storage#51]
This is a very trivial issue, and maybe there's a very good reason not to do this, but given that “box” in CSS has a very specific definition that's used in pretty much every CSS spec and is embedded as a term in some of its APIs, one might consider renaming the Storage concept of “box” to something else?

**Comment by fantasai** [comment]
Or at least maybe not exporting the definition if it's a spec-internal term...

**Comment by annevk** [comment]
@inexorabletash @shuangMoz @jakearchibald thoughts? I'm happy to rename this. We'll need to export something since eventually other specifications will use it.

Bin doesn't seem appropriate since it's not trash. I could prefix it with storage perhaps. So "storage box".

Other alternative: store. But that is also used a lot I suspect.

**Comment by domenic** [comment]
FWIW the "trash" association with "bin" is probably more of a regional thing; it isn't in the dictionary. (But I can believe that some places in the world use "trash bin" like Americans use "garbage can".)

**Comment by inexorabletash** [comment]
I'm fine with a rename, but no strong preferences.

"store" will get confused with Indexed DB's [object store](https://w3c.github.io/IndexedDB/#object-store-construct)

Internally, Chrome has "partition" for a different concept so I'd vote against that one too.

I'd casually use "bucket" to describe this, but there may be connotations (buckets get full, buckets leak, etc)

**Comment by annevk** [comment]
I'm okay with "bucket".

**Comment by fantasai** [comment]
We have trash bin and recycling bin here in the US, and they're understandably the most common, but we also have other kinds of bins. :) The plastic things in here are all called bins: https://www.northerntool.com/images/product/2000x2000/502/50273_2000x2000.jpg

**Comment by annevk** [comment]
I created #52 to address this.

**Comment by annevk** [comment]
Per feedback in the PR it seems like it'll be "bucket" after all.
