### ISSUE TITLE
Define task source

### ISSUE THREAD

**Issue by annevk** [whatwg/storage#89]
Not sure what to use here. I guess we should also define the document. Is

> If the task is being queued by or for a script, then return the script's settings object's responsible document.

really correct here?

cc @domenic

**Comment by domenic** [comment]
That's not super-correct; it's just a fallback. @dtapuska had some ideas here for how to replace the implied document stuff in cases where there wasn't an HTML element in play, but I think it'll generally boil down to something like the relevant global object's associated Document.
