### ISSUE TITLE
Allow script to request permission only if there would be no prompt

### ISSUE THREAD

**Issue by davidsgrogan** [whatwg/storage#9]
We've heard from sites that they don't want to prompt the user for this capability and would only request permission if the browser would autogrant it. We are planning on autogranting if the origin has a high "engagement score" for this user. But we want the origin to have to request the permission, we aren't going to opt the origin in to persistence if it doesn't ask for it.

So we'd like a way for an origin to request permission only if the user wouldn't be prompted. One way would be to add an optional parameter to requestPersistent(): `requestPersistent{"noPrompt": true})`. Another would be to add a fourth permission, `"wouldBeAutoGranted"` or something, that would let the site know that `requestPersistent()` would change the default box's mode to "persistent" without prompting. I'm sure there are other strong possibilities too.

/cc @inexorabletash

**Comment by annevk** [comment]
Why not set the permission to "granted"? That would make `persistentPermission()` return "granted" and `requestPersistent()` would not prompt and change your storage to be persistent.

**Comment by inexorabletash** [comment]
If a site assumed `persistentPermission() => "granted"` indicates the storage is persistent it would not bother to call `requestPersistent()`:

```js
navigator.storage.persistentPermission()
  .then(function(permission) {
    if (permission === 'default') {
      return navigator.storage.requestPermission();
    } else if (permission === 'denied') {
      // oh well
      return false;
    } else if (permission === 'granted') {
      // yay!
      return true;
    }
  })
  .then(function(hasPersistent) {
   // ...
  });
```
Now, obviously, if the goal is just to get the permission, the above is silly - the script should simply call `requestPermission()` and be done with it. But an extremely common practice (on mobile, at least) is to determine if the user will be prompted and, if so, have a UX flow that explains the benefits of accepting before the request is made.

If it's not the case that `granted` implies that the storage is persistent, it seems like we need Yet Another Way to query the state without changing it, so it's possible for the origin to introspect.

**Comment by annevk** [comment]
I suggested `persistent()` somewhere. That seems more consistent with other APIs? 

However, you can always invoke `requestPersistent()` safely after seeing "granted". Adding an additional argument to `requestPersistent()` seems okay too, but not really nice.

**Comment by inexorabletash** [comment]
> I suggested `persistent()` somewhere

I don't want to bloat the API, but that seem the "correct" thing to have to me.

> However, you can always invoke `requestPersistent()` safely after seeing "granted".

Agreed. That seems like something we'd want to document heavily, as it may not be clear to developers.

(This edge of the spec isn't blocking progress or use cases, so we can wait for more feedback here.)

**Comment by domenic** [comment]
I'm a little confused what the issue is here. @inexorabletash, you said

> If a site assumed persistentPermission() => "granted" indicates the storage is persistent it would not bother to call requestPersistent()

Is that actually a bad thing in any way? It seems fine. The idea is that authors could write:

```js
navigator.storage.persistentPermission()
  .then(function(permission) {
    return permission === 'granted';
  })
  .then(function(hasPersistent) {
   // ...
  });
```

and it would be equivalent to

```js
navigator.storage.persistentPermissionOnlyIfNoPrompt()
  .then(function(hasPersistent) {
   // ...
  });
```

**Comment by annevk** [comment]
@domenic I don't follow your code. `persistentPermission()` just returns the permission.

**Comment by domenic** [comment]
@annevk right. And if it's already "granted", then that means you can use persistent storage.

**Comment by annevk** [comment]
You mean that if a user agent decides to grant a permission to a site it must also automatically put it in use? That you have permission to do something, doesn't automatically mean your normal storage box is now a persistent one.

**Comment by domenic** [comment]
... WAT.

That is seriously bizarre.

I would interpret "permission granted" to mean "the system will behave the same as if the user had been prompted and then clicked 'grant this origin permission'."

You are instead saying that "permission granted" really means "you could get permission if you called requestPersistent()"??

This is crazysauce.

I'd suggest renaming "granted" to "will-be-granted" to make this clearer.

**Comment by annevk** [comment]
I don't understand. There's a concept of "permission" and there's a concept of changing the box. `requestPersistent()` requests permission (if not already granted) and then, once obtained, changes the box. You seem to be coupling the permission with changing the box which doesn't quite make sense to me.

**Comment by domenic** [comment]
I am coupling the permission with what happens when the user grants permission. My understanding is that when the user grants permission, the box becomes persistent.

**Comment by annevk** [comment]
Yes, but what if the user agent decides to grant permission to a site. Should it also change the box? Compare with a user agent granting geolocation to a set of origins. Should these origins all be handed location data unasked? Or should asking for a location simply not prompt in such a scenario?

**Comment by domenic** [comment]
For sure! I think it would be bizarre if user agents (agents acting on behalf of the user) triggered different behavior than users themselves!

> Compare with a user agent granting geolocation to a set of origins. Should these origins all be handed location data unasked? Or should asking for a location simply not prompt in such a scenario?

I don't understand the functional difference.

**Comment by annevk** [comment]
Then, consider the permission API. Would you expect granting permission through that API to have the side effect of changing the box? It seems rather bizarre what you are proposing.

**Comment by domenic** [comment]
Yes, I absolutely would. Saying that permission-granting works differently when users do it versus when APIs do it is scary. It means as a developer I have no coherent mental model for how permission granting works, when using the API.

**Comment by annevk** [comment]
I don't understand your point. It works the same either way. But we shouldn't make permission granting have side effects like you suggest. That is bad design.

**Comment by domenic** [comment]
When a user clicks "grant permission", it changes the box, right?

**Comment by davidsgrogan** [comment]
I fear that Domenic's confusion will be echoed by many developers and indicates that even if this "feels" the most correct to us, it will not feel correct to developers.

**Comment by annevk** [comment]
That depends on how the user gave permission. There's a difference between granting a site the permission to store things persistently and the site using that permission. I think everyone but you in this discussion has that model in mind, but I would be happy to be corrected.

To me it makes no sense if a generic API such as `permissions.get()` or some such would end up changing the box, which requires detailed domain knowledge. That would seem like a bad layering violation.

**Comment by davidsgrogan** [comment]
I do have that model in mind but it took a sitdown conversation with @inexorabletash to understand it. I don't think it will be clear to developers.

**Comment by annevk** [comment]
@davidsgrogan that is fair. My issue is that going forward I think we want these to be separate as otherwise multiple boxes will get all kinds of tricky.

**Comment by domenic** [comment]
> To me it makes no sense if a generic API such as permissions.get() or some such would end up changing the box, which requires detailed domain knowledge. That would seem like a bad layering violation.

I think the model here is very different from the one I have in mind. My model is as follows:

- The UA has a permission, which is roughly "can write to persistent storage" or "cannot write to persistent storage."
- Every time you do a write, the UA asks "what permission do I have?" if it's "can write to persistent storage," then it goes in the persistent box.

As such, granting permission does not actually have any domain-related side effects. It just changes a boolean which is later consulted by the domain-specific code.

I guess that is not how the spec is written right now. So then my question is: why? Is the spec-as-it-is-now model more aligned with browsers in some way?

**Comment by domenic** [comment]
I guess I see how it is different. The spec as it is now lets you convert old stuff to be persistently stored.

**Comment by annevk** [comment]
Right and that is important. It's not like we can divvy up your existing IDB or localStorage.

**Comment by domenic** [comment]
I guess I will try to think about this more and see if I come up with anything to contribute. Right now my only thoughts are that if everything was renamed to be way more verbose, I would not be confused:

- `persistentPermission` -> `abilityToMakeBoxesPersistentPermission`
- `requestPersistent` -> `makeBoxPersistent`
- Add `isBoxPersistent` so that we don't think that the permission is representative of things.

Maybe that last one is actually what is missing. E.g. `navigator.storage.isPersistent`. Then I would realize that this condition of being persistent is different from the condition of having the permission to do so. So the API call only changes the latter, but user interaction changes both.

Although now I am confused about why `navigator.storage.estimate()` even works at all once you've made the box persistent. I'll go read the spec more.

**Comment by annevk** [comment]
Right, `isPersistent()` or simply `persistent()` is what I proposed earlier on. Changing the names of some of the other methods seems reasonable and doable too. `estimate()` stays around because a box is origin-scoped, whereas quotas can be eTLD+1-scoped.

**Comment by annevk** [comment]
I was going to propose renaming `requestPersistent()` to `makePersistent()`, but `requestFullscreen()` is fairly similar. Is there a reason why "request" is less clear here?

Shall I add `isPersistent()`?

**Comment by davidsgrogan** [comment]
In https://github.com/whatwg/storage/issues/9#issuecomment-132338881 you say
> I suggested persistent() somewhere. That seems more consistent with other APIs?

Which other APIs did you have in mind? We'd like to ensure that their usage model is similar to this one.

**Comment by domenic** [comment]
> Is there a reason why "request" is less clear here?

I think maybe it's because I expect requestPersistent() to have the same affect as when the UA requests persistent storage (i.e., pops up an infobar, or similar).

Maybe a realistic set of names is

- makePersistent() (requestMakePersistent??)
- makePersistentPermission()
- persistent boolean getter

**Comment by annevk** [comment]
All three have to be asynchronous @domenic.

@davidsgrogan I think what I meant was that changing the set of permission values or the way you invoke `requestPersistent()` would not be very consistent and unprecedented.

**Comment by annevk** [comment]
@domenic to be clear, request does popup an infobar (but only if the permission is not granted). I'll add persistent() though.
